/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.Student;
import model.KRS;
import model.Lecturer;
import model.Course;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;


   



/**
 * @author windari
 */

  public class inputnilai extends javax.swing.JFrame {
    ArrayList<Student> listMahasiswa = new ArrayList<>();
    ArrayList<Course> listMK = new ArrayList<>();
    ArrayList<Lecturer> listLecturer = new ArrayList<>();
    final String[] semester = {"1", "2", "3"};
    final DefaultComboBoxModel comboModelSM = new DefaultComboBoxModel(semester);
    DefaultComboBoxModel<Student> comboModelMhs = new DefaultComboBoxModel<>();
    DefaultComboBoxModel<Course> comboModelCourse = new DefaultComboBoxModel<>();
    DefaultComboBoxModel<Lecturer> comboModelLecturer = new DefaultComboBoxModel<>();
    Student selecttedStudent;
    Course selecteCourse;
    KRS krs;
    Lecturer selecLecturer;
    private Student selectedStudent;
    private Course selectedCourse; 
    private Lecturer selectedLecturer;
    
    
       
       
        
    /**
     * Creates new form InputNilai
     */
    public inputnilai(){
        initComponents();
        listMahasiswa.add(new Student("199000299","Andi","001", "Ilmu Komputer"));
        listMahasiswa.add(new Student("198003272","Agus Jaya","002", "Ilmu Komputer"));
        listMahasiswa.add(new Student("197690246","Deni Mudia","003", "Ilmu Komputer"));
        listMK.add(new Course("010", "OOP", 3, 2));
        listMK.add(new Course("011", "English", 3, 2));
        listMK.add(new Course("012", "Web", 3, 2));
        listMK.add(new Course("013", "Mobile", 3, 2));
        listLecturer.add(new Lecturer("012", "Agus", "092290", "web"));
        listLecturer.add(new Lecturer("013", "wahyu wijaya", "092290", "OOP"));
       listLecturer.add(new Lecturer("014", "wayan marti", "092290", "kalkulus"));
        for (Lecturer item: listLecturer){
            comboModelLecturer.addElement(item);
        }
        for (Student student : listMahasiswa) {
           comboModelMhs.addElement(student);
        }
        for (Course course : listMK) {
            comboModelCourse.addElement(course);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxmhs = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNIM = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxMK = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabelSKS = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldSIKAP = new javax.swing.JTextField();
        jTextFieldUTS = new javax.swing.JTextField();
        jTextFieldUAS = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxSM = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jButtonADD = new javax.swing.JButton();
        jLabelNILAIHURUF = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxdosen = new javax.swing.JComboBox<>();
        jButtonDelet = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonCange = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("identitas mahasiswa");

        jLabel3.setText("nama");

        jComboBoxmhs.setModel(comboModelMhs);
        jComboBoxmhs.addActionListener(this::jComboBoxmhsActionPerformed);

        jLabel4.setText("NIM & Perodi");

        jTextFieldNIM.setText("nim");
        jTextFieldNIM.addActionListener(this::jTextFieldNIMActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(49, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxmhs, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxmhs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 34, Short.MAX_VALUE))
        );

        jLabel1.setText("Form Input Nilai");

        jLabel5.setText("Identitas Matakuliah");

        jLabel6.setText("Matakuliah");

        jComboBoxMK.setModel(comboModelCourse);
        jComboBoxMK.addActionListener(this::jComboBoxMKActionPerformed);

        jLabel7.setText("Kode dan SKS");

        jLabelSKS.setText("Kode SKS");

        jLabel8.setText("Nilai");

        jTextFieldSIKAP.setText("0");
        jTextFieldSIKAP.addActionListener(this::jTextFieldSIKAPActionPerformed);

        jTextFieldUTS.setText("0");

        jTextFieldUAS.setText("0");
        jTextFieldUAS.addActionListener(this::jTextFieldUASActionPerformed);

        jLabel9.setText("Semester");

        jComboBoxSM.setModel(comboModelSM);
        jComboBoxSM.addActionListener(this::jComboBoxSMActionPerformed);

        jLabel10.setText("Nilai Huruf");

        jButtonADD.setText("Add");
        jButtonADD.addActionListener(this::jButtonADDActionPerformed);

        jLabelNILAIHURUF.setText("Nilai Huruf");

        jLabel11.setText("Dosen");

        jComboBoxdosen.setModel(comboModelLecturer);
        jComboBoxdosen.addActionListener(this::jComboBoxdosenActionPerformed);

        jButtonDelet.setText("DELETE");
        jButtonDelet.addActionListener(this::jButtonDeletActionPerformed);

        jButtonUpdate.setText("UPDATE");

        jButtonCange.setText("CHANGE");
        jButtonCange.addActionListener(this::jButtonCangeActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxSM, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jButtonCange, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonADD, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(25, 25, 25)
                                .addComponent(jButtonDelet)
                                .addGap(124, 124, 124))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jTextFieldSIKAP, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldUTS, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldUAS, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jComboBoxMK, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBoxdosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelSKS))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelNILAIHURUF))
                            .addComponent(jLabel11))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextFieldSIKAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldUTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldUAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jComboBoxSM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jComboBoxMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelSKS)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxdosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabelNILAIHURUF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonADD)
                    .addComponent(jButtonUpdate)
                    .addComponent(jButtonCange)
                    .addComponent(jButtonDelet))
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIM", "NAMA", "Matakuliah", "SKS", "Nilai", "Dosen"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxmhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxmhsActionPerformed
         // TODO add your handling code here:
         this.selectedStudent=(Student)jComboBoxmhs.getSelectedItem();
         if(selectedStudent != null) {
         jTextFieldNIM.setText(
        selectedStudent.getNim() +
        " | Prodi : " +
        selectedStudent.getStudyProgram()
    );
}
    }//GEN-LAST:event_jComboBoxmhsActionPerformed

    private void jComboBoxMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMKActionPerformed
        // TODO add your handling code here:
       this.selectedCourse = (Course) jComboBoxMK.getSelectedItem();

    if(selectedCourse != null){
        jLabelSKS.setText(
            selectedCourse.getCode() +
            " | SKS : " +
            selectedCourse.getSKS()
        );
    }
    }//GEN-LAST:event_jComboBoxMKActionPerformed
private void setKRS() {
    int uas=Integer.parseInt(jTextFieldUAS.getText());
    int uts=Integer.parseInt(jTextFieldUTS.getText());
    int sikap=Integer.parseInt(jTextFieldSIKAP.getText());
    double rataRata=(uas+uts+sikap)/3.0;
    
    // Perbaikan bagian merah
    this.krs = new KRS();
    this.krs.setCourse(selectedCourse);
    this.krs.setNilaiAkhir(rataRata); 
    
    this.krs.setLecturer(selectedLecturer);
    
    
}
        
    private void jTextFieldSIKAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSIKAPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSIKAPActionPerformed

    private void jButtonADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonADDActionPerformed


    if(selectedStudent == null || selectedCourse == null){
        javax.swing.JOptionPane.showMessageDialog(this,
                "Pilih mahasiswa dan mata kuliah terlebih dahulu!");
        return;
    }

    setKRS();

    selectedStudent.addKRS(krs);

    javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) jTable1.getModel();

    model.addRow(new Object[]{
        selectedStudent.getNim(),
        selectedStudent.getName(),
        selectedCourse.getCourseName(),
        selectedCourse.getSKS(),
        krs.getNilaiAkhir(),
        selectedLecturer.getName()
    });

    jLabelNILAIHURUF.setText(String.valueOf(krs.getNilaiAkhir()));
   
    }//GEN-LAST:event_jButtonADDActionPerformed


    private void jTextFieldUASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUASActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUASActionPerformed

    private void jComboBoxSMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSMActionPerformed
        // TODO add your handling code here:
        setKRS();
        jLabelNILAIHURUF.setText(String.valueOf(this.krs.getNilaiAkhir())); 
}

        private void getNilaiAkhir() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        
    }//GEN-LAST:event_jComboBoxSMActionPerformed

    private void jTextFieldNIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNIMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNIMActionPerformed

    private void jComboBoxdosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxdosenActionPerformed
        // TODO add your handling code here:

        this.selectedLecturer = (Lecturer) jComboBoxdosen.getSelectedItem();
    }//GEN-LAST:event_jComboBoxdosenActionPerformed

    private void jButtonCangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCangeActionPerformed
       javax.swing.JOptionPane.showMessageDialog(
            this,
            "Fitur Update belum dibuat.");
// TODO add your handling code here:
    }//GEN-LAST:event_jButtonCangeActionPerformed

    private void jButtonDeletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletActionPerformed
        javax.swing.table.DefaultTableModel model =
        (javax.swing.table.DefaultTableModel) jTable1.getModel();

    int row = jTable1.getSelectedRow();

    if(row!=-1){
        model.removeRow(row);
    }
    }//GEN-LAST:event_jButtonDeletActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
           
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new inputnilai().setVisible(true));
    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonADD;
    private javax.swing.JButton jButtonCange;
    private javax.swing.JButton jButtonDelet;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox<Course> jComboBoxMK;
    private javax.swing.JComboBox<String> jComboBoxSM;
    private javax.swing.JComboBox<Lecturer> jComboBoxdosen;
    private javax.swing.JComboBox<Student> jComboBoxmhs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelNILAIHURUF;
    private javax.swing.JLabel jLabelSKS;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldNIM;
    private javax.swing.JTextField jTextFieldSIKAP;
    private javax.swing.JTextField jTextFieldUAS;
    private javax.swing.JTextField jTextFieldUTS;
    // End of variables declaration//GEN-END:variables
  }
    

